# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        self.statusbar = None
        self.menubar = None
        self.pause_btn = None
        self.stop_btn = None
        self.start_btn = None
        self.signal_selector = None
        self.signal_selector_lbl = None
        self.timer_editor_lbl = None
        self.timer_editor = None
        self.timer_state = None
        self.central_widget = None

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(570, 315)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("centralwidget")
        self.timer_state = QtWidgets.QLabel(self.central_widget)
        self.timer_state.setGeometry(QtCore.QRect(175, 10, 220, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.timer_state.setFont(font)
        self.timer_state.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_state.setObjectName("timer_state")
        self.timer_editor = QtWidgets.QTimeEdit(self.central_widget)
        self.timer_editor.setGeometry(QtCore.QRect(30, 140, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timer_editor.setFont(font)
        self.timer_editor.setObjectName("timer_editor")
        self.timer_editor_lbl = QtWidgets.QLabel(self.central_widget)
        self.timer_editor_lbl.setGeometry(QtCore.QRect(30, 100, 190, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timer_editor_lbl.setFont(font)
        self.timer_editor_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_editor_lbl.setObjectName("timer_editor_lbl")
        self.signal_selector_lbl = QtWidgets.QLabel(self.central_widget)
        self.signal_selector_lbl.setGeometry(QtCore.QRect(300, 100, 190, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.signal_selector_lbl.setFont(font)
        self.signal_selector_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.signal_selector_lbl.setObjectName("signal_selector_lbl")
        self.signal_selector = QtWidgets.QComboBox(self.central_widget)
        self.signal_selector.setGeometry(QtCore.QRect(300, 140, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.signal_selector.setFont(font)
        self.signal_selector.setObjectName("signal_selector")
        self.signal_selector.addItem("")
        self.signal_selector.addItem("")
        self.start_btn = QtWidgets.QPushButton(self.central_widget)
        self.start_btn.setGeometry(QtCore.QRect(30, 245, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.stop_btn = QtWidgets.QPushButton(self.central_widget)
        self.stop_btn.setGeometry(QtCore.QRect(440, 245, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.pause_btn = QtWidgets.QPushButton(self.central_widget)
        self.pause_btn.setGeometry(QtCore.QRect(235, 245, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pause_btn.setFont(font)
        self.pause_btn.setObjectName("pause_btn")
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timer_state.setText(_translate("MainWindow", "00:00:00"))
        self.timer_editor.setDisplayFormat(
            _translate("MainWindow", "HH:mm:ss"))
        self.timer_editor_lbl.setText(
            _translate("MainWindow", "Установить таймер"))
        self.signal_selector_lbl.setText(
            _translate("MainWindow", "Установить сигнал"))
        self.signal_selector.setItemText(
            0, _translate("MainWindow", "Без звука"))
        self.signal_selector.setItemText(
            1, _translate(
                "MainWindow", "Выбрать с устройства"))
        self.start_btn.setText(_translate("MainWindow", "Старт"))
        self.stop_btn.setText(_translate("MainWindow", "Стоп"))
        self.pause_btn.setText(_translate("MainWindow", "Пауза"))
